### Create todo

POST http://localhost:8080/todos
Content-Type: application/json

{
  "name": "Cook beef with mushroom",
  "done": false
}

### Get all todos

GET http://localhost:8080/todos
Content-Type: application/json

### Update todo

PUT http://localhost:8080/todos
Content-Type: application/json

{
  "id": "2",
  "name": "Study Java and Spring Boot",
  "isDone": true
}